version: '0.2'
phases:
  install:
    runtime-versions:
      nodejs: 18.20.4
    commands:
      - echo Installing dependencies...
      - npm install --force
  pre_build:
    commands:
      - echo Building project...
      - npm run build --verbose
  build:
    commands:
      - echo ID_CG9sOU0b
      - echo Creating tar.gz archive of build files...
      - cd dist
      - tar -czvf ../PLN1000685.tar.gz *
  post_build:
    commands:
      - echo Pushing artifacts...
artifacts:
  files:
    - PLN1000685.tar.gz
